#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-heroku
Version  : 2.41.0
Release  : 3
URL      : https://rubygems.org/downloads/heroku-2.41.0.gem
Source0  : https://rubygems.org/downloads/heroku-2.41.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-heroku-bin
BuildRequires : ruby
BuildRequires : rubygem-launchy
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rest-client
BuildRequires : rubygem-rubyzip

%description
Heroku CLI
==========
The Heroku CLI is used to manage Heroku apps from the command line.

%package bin
Summary: bin components for the rubygem-heroku package.
Group: Binaries

%description bin
bin components for the rubygem-heroku package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n heroku-2.41.0
gem spec %{SOURCE0} -l --ruby > rubygem-heroku.gemspec

%build
gem build rubygem-heroku.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
heroku-2.41.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/heroku-2.41.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/bin/heroku
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/data/cacert.pem
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/auth.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/cli.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/client.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/client/cisaurus.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/client/heroku_postgresql.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/client/pgbackups.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/client/rendezvous.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/client/ssl_endpoint.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/account.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/accounts.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/addons.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/apps.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/auth.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/certs.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/config.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/db.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/domains.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/drains.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/fork.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/git.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/help.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/keys.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/labs.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/logs.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/maintenance.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/pg.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/pgbackups.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/plugins.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/ps.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/regions.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/releases.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/run.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/sharing.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/ssl.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/stack.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/status.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/update.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/command/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/deprecated.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/deprecated/help.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/distribution.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/excon.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/helpers/heroku_postgresql.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/helpers/log_displayer.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/plugin.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/updater.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/heroku/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/lib/vendor/heroku/okjson.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/helper/legacy_help.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/auth_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/client/heroku_postgresql_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/client/pgbackups_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/client/rendezvous_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/client/ssl_endpoint_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/client_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/addons_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/apps_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/auth_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/base_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/certs_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/config_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/db_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/domains_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/drains_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/fork_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/git_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/help_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/keys_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/labs_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/logs_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/maintenance_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/pg_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/pgbackups_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/plugins_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/ps_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/releases_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/run_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/sharing_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/stack_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/status_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command/version_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/command_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/helpers/heroku_postgresql_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/helpers_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/plugin_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/heroku/updater_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/spec.opts
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/support/display_message_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-2.41.0/spec/support/openssl_mock_helper.rb
/usr/lib64/ruby/gems/2.3.0/specifications/heroku-2.41.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/heroku
