#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-heroku
Version  : 3.43.12
Release  : 8
URL      : https://rubygems.org/downloads/heroku-3.43.12.gem
Source0  : https://rubygems.org/downloads/heroku-3.43.12.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-heroku-bin
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
![](https://d4yt8xl9b7in.cloudfront.net/assets/home/logotype-heroku.png) Heroku CLI
==========

%package bin
Summary: bin components for the rubygem-heroku package.
Group: Binaries

%description bin
bin components for the rubygem-heroku package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n heroku-3.43.12
gem spec %{SOURCE0} -l --ruby > rubygem-heroku.gemspec

%build
export LANG=C
gem build rubygem-heroku.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
heroku-3.43.12.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/heroku-3.43.12.gem
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/README.md
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/bin/heroku
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/data/cacert.pem
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/analytics.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/api/apps_v3.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/api/domains_v3.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/api/organizations_apps_v3.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/api/spaces_v3.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/auth.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/cli.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/client.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/client/heroku_postgresql.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/client/heroku_postgresql_backups.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/client/organizations.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/client/rendezvous.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/client/ssl_endpoint.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/addons.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/apps.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/auth.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/buildpacks.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/certs.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/config.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/domains.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/features.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/help.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/keys.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/labs.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/logs.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/members.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/orgs.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/pg.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/pg_backups.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/pgbackups.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/plugins.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/ps.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/regions.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/releases.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/run.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/stack.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/update.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/command/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/config.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/deprecated.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/deprecated/help.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/git.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/helpers/addons/api.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/helpers/addons/display.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/helpers/addons/resolve.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/helpers/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/helpers/heroku_postgresql.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/helpers/log_displayer.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/helpers/pg_diagnose.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/helpers/pg_dump_restore.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/http_instrumentor.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/jsplugin.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/open_ssl.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/plugin.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/rollbar.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/updater.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/heroku/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/lib/vendor/heroku/okjson.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/fixtures/heroku-client-3.9.7.zip
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/helper/legacy_help.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/helper/pg_dump_restore_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/auth_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/client/heroku_postgresql_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/client/rendezvous_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/client/ssl_endpoint_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/client_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/command/addons_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/command/apps_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/command/auth_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/command/base_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/command/buildpacks_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/command/certs_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/command/config_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/command/domains_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/command/help_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/command/keys_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/command/labs_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/command/logs_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/command/orgs_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/command/pg_backups_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/command/pg_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/command/pgbackups_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/command/plugins_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/command/ps_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/command/releases_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/command/run_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/command/stack_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/command/version_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/command_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/git_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/helpers/env_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/helpers/heroku_postgresql_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/helpers_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/jsplugin_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/open_ssl_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/plugin_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/heroku/updater_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/spec.opts
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/support/addons_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/support/display_message_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/support/openssl_mock_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-3.43.12/spec/support/organizations_mock_helper.rb
/usr/lib64/ruby/gems/2.3.0/specifications/heroku-3.43.12.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/heroku
